### ISSUE TITLE
Question about the formula (2) and (3)?

### ISSUE THREAD

**Issue by dsj96** [OpenDFM/Rememberer#1]
[Rememberer](https://github.com/OpenDFM/Rememberer) is great, equipping LLM with an experience memory module and utilizing reinforcement learning to update and retrieve examplors. I have some questions about how to update experience memory on formula (2) and (3). 

In formula (2) , $Q(g,o_{t},a_{t})=Q^{'}(g,o_{t},a_{t})$, What do  $Q$ and  $Q^{'}$ represent respectively.  According formula(1), I think that $Q$ denotes the origial $q$ value, and $Q^{'}$ denotes the updated $q$ value. Do I understand correctly? 

In formula (3) , $Q(g,o_{t},a_{t}) ← (1 − α)Q(g,o_{t},a_{t})  +  αQ^{'}(g,o_{t},a_{t})$,  What does `←` represent in formula (3). If `←` means `=`, then Formula (2) and Formula (3) are exactly the same.

Due to the above two reasons, I am not very familiar with Formula 4. Can you explain it to me？

**Comment by zdy023** [comment]
Thanks for your question! 

$Q^\prime$ does denote the updated $q$ value. Your understanding is correct. $\leftarrow$ means "updates to", or just `=` in programming language. How

**Comment by zdy023** [comment]
Thanks for your question! 

$Q^\prime$ does denote the new $q$ estimation. Your understanding is correct. 

$\leftarrow$ means "update to", or just `=` in programming language. 

However, Formula (2) and Formula (3) are not equal. They will be the same if the learning rate $\alpha$ is $1/N$ as in our experiments. However, the learning rate may be set to another value, like a moderate constant, or subject to more complex attenuation functions. The suitable form of $\alpha$ may depend on the specific environment.

In our experiments, $\alpha$ is set to $1/N$ for we assume that the two test environments are stationary. Therefore, we can assign an equal weight for the estimations across the time.

Formula (4) doesn't depend on Formulae (2) and (3). It is an update to Formula (1). As Bellman optimization equation leverages a recursive form, it requires a number of steps to make the estimation converge. However, if we make use of more real-time rewards for the estimation, we can make it converge faster. This is called "n-step bootstrapping".

I hope my reply will help you. Thanks again for your interest!

**Comment by dsj96** [comment]
Thank you for your detailed reply.
Formula (2) and Formula (3) are exactly the same means (What confuses me is):
$Q(g,o_{t},a_{t})                ← (1 − α)Q(g,o_{t},a_{t})  +  αQ^{'}(g,o_{t},a_{t})$
$(1-1 + α)Q(g,o_{t},a_{t})  ←  αQ^{'}(g,o_{t},a_{t})$
$αQ(g,o_{t},a_{t})  ←  αQ^{'}(g,o_{t},a_{t})$
Therefore, I think formula (2) and formula (3) are exactly the same.

Then, in formula (2) and formula (3), 
$Q(g,o_{t},a_{t})$ is on the left of `=`, 
$Q^{'}(g,o_{t},a_{t})$ is on the right of `=`.
It seems to be using the updated $Q^{'}$ value  to calculate the original $Q$ value.

**Comment by zdy023** [comment]
$\leftarrow$ means "**update to**". This is an *algorithm operation*, but **not** the *mathematical relation* "equality*. You **cannot** perform any value transformation to the left side, such as simultaneous adding/multiplying, expanding, *etc.* The left side of $\leftarrow$ indicates a direction, a slot, a pointer, a reference, but **not a value**. You are supposed to have a review to the basic concepts like "lvalue" and "rvalue" and try to distinguish them.

**Comment by dsj96** [comment]
Oh! I think I understand now. thank you!

**Comment by zdy023** [comment]
I'm glad that your question has been handled. I will close this issue.
