### ISSUE TITLE
Question for the source code

### ISSUE THREAD

**Issue by Chreer** [OpenDFM/Rememberer#2]
I‘ve tried to implement your work but I met a problem as shown in Figure below. Is it caused by using a wrong version of Python? 
![image](https://github.com/OpenDFM/Rememberer/assets/97589171/ceedf897-8bfb-43c8-b7ba-e9b2f46410db)

**Comment by zdy023** [comment]
The experiments are conducted on Python 3.8. If you're using a lower version, you can try to switch to a version >= 3.8. This is a problem w.r.t. type hinting in Python. If it remains, you may try to remove these type hints. They should take no effects at runtime.
