### ISSUE TITLE
No such file or directory: 'openaiconfig.yaml'

### ISSUE THREAD

**Issue by xinhaoH** [OpenDFM/Rememberer#3]
Hello, you didn't provide the file "openaiconfig.yaml" to run webshop.py/wikihow.py.
Maybe only openai api_key is needed?
Thanks a lot!

**Comment by zdy023** [comment]
Hello, this file is not updated to GitHub, as there is only an OpenAI API key stored in it. You can simply create a file named `openaiconfig.yaml` with contents like

```yaml
api_key: sk-xxxx
```

Thanks for your interest. We will add a template of this file in the repository.
